In [101]:
import pandas as pd
import numpy as np

In [102]:
data=pd.read_csv(r"C:\fsdsmendtoend\notebooks\data\train.csv\train.csv")

In [103]:
data.drop("id",axis=1,inplace=True)

In [104]:
data

        carat        cut color clarity  depth  table     x     y     z  price
0        1.52    Premium     F     VS2   62.2   58.0  7.27  7.33  4.55  13619
1        2.03  Very Good     J     SI2   62.0   58.0  8.06  8.12  5.05  13387
2        0.70      Ideal     G     VS1   61.2   57.0  5.69  5.73  3.50   2772
3        0.32      Ideal     G     VS1   61.6   56.0  4.38  4.41  2.71    666
4        1.70    Premium     G     VS2   62.6   59.0  7.65  7.61  4.77  14453
...       ...        ...   ...     ...    ...    ...   ...   ...   ...    ...
193568   0.31      Ideal     D    VVS2   61.1   56.0  4.35  4.39  2.67   1130
193569   0.70    Premium     G    VVS2   60.3   58.0  5.75  5.77  3.47   2874
193570   0.73  Very Good     F     SI1   63.1   57.0  5.72  5.75  3.62   3036
193571   0.34  Very Good     D     SI1   62.9   55.0  4.45  4.49  2.81    681
193572   0.71       Good     E     SI2   60.8   64.0  5.73  5.71  3.48   2258

[193573 rows x 10 columns]

In [105]:
X=data.drop("price",axis=1)

In [106]:
y=data[["price"]]

In [107]:
X

        carat        cut color clarity  depth  table     x     y     z
0        1.52    Premium     F     VS2   62.2   58.0  7.27  7.33  4.55
1        2.03  Very Good     J     SI2   62.0   58.0  8.06  8.12  5.05
2        0.70      Ideal     G     VS1   61.2   57.0  5.69  5.73  3.50
3        0.32      Ideal     G     VS1   61.6   56.0  4.38  4.41  2.71
4        1.70    Premium     G     VS2   62.6   59.0  7.65  7.61  4.77
...       ...        ...   ...     ...    ...    ...   ...   ...   ...
193568   0.31      Ideal     D    VVS2   61.1   56.0  4.35  4.39  2.67
193569   0.70    Premium     G    VVS2   60.3   58.0  5.75  5.77  3.47
193570   0.73  Very Good     F     SI1   63.1   57.0  5.72  5.75  3.62
193571   0.34  Very Good     D     SI1   62.9   55.0  4.45  4.49  2.81
193572   0.71       Good     E     SI2   60.8   64.0  5.73  5.71  3.48

[193573 rows x 9 columns]

In [108]:
y

        price
0       13619
1       13387
2        2772
3         666
4       14453
...       ...
193568   1130
193569   2874
193570   3036
193571    681
193572   2258

[193573 rows x 1 columns]

In [109]:
categorical_columns=X.select_dtypes(include="object").columns
numerical_columns=X.select_dtypes(exclude='object').columns

In [110]:
numerical_columns

Index(['carat', 'depth', 'table', 'x', 'y', 'z'], dtype='object')

In [111]:
# Define the custom ranking for each ordinal variable
cut_categories = ['Fair', 'Good', 'Very Good','Premium','Ideal']
color_categories = ['D', 'E', 'F', 'G', 'H', 'I', 'J']
clarity_categories = ['I1','SI2','SI1','VS2','VS1','VVS2','VVS1','IF']

In [112]:
from sklearn.impute import SimpleImputer ## HAndling Missing Values
from sklearn.preprocessing import StandardScaler # HAndling Feature Scaling
from sklearn.preprocessing import OrdinalEncoder # Ordinal Encoding
## pipelines
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [113]:
# this is for feature engineering , to do multiple steps ata single shot

num_pipeline=Pipeline(

    steps=[
        ('imputer', SimpleImputer()),
        ('scaler', StandardScaler())
    ]
)

In [114]:
cat_pipeline=Pipeline(
    steps=[
        ('imputer', SimpleImputer(strategy="most_frequent")),
        ('ordinalencoder',OrdinalEncoder(categories=[cut_categories,color_categories,clarity_categories]))
    ]
)

In [115]:
preprocessor=ColumnTransformer(
    [
        ("num_pipeline",num_pipeline, numerical_columns),
        ("cat_pipeline",cat_pipeline,categorical_columns)
    ]
)

In [116]:
# train test split

from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,y, test_size=0.30)

In [117]:
preprocessor.fit_transform(X_train)

array([[-0.60430108,  0.62601518, -1.16060151, ...,  4.        ,
         0.        ,  3.        ],
       [ 0.56087906,  0.3486436 , -0.63837898, ...,  4.        ,
         4.        ,  2.        ],
       [ 0.12933086,  0.71847237, -0.11615646, ...,  4.        ,
         0.        ,  1.        ],
       ...,
       [ 0.73349833, -1.31558585,  0.40606606, ...,  2.        ,
         3.        ,  3.        ],
       [-1.05742669,  0.4411008 ,  0.40606606, ...,  4.        ,
         1.        ,  5.        ],
       [-1.18689115,  0.53355799,  0.40606606, ...,  2.        ,
         2.        ,  5.        ]])

In [118]:
preprocessor.transform(X_test)

array([[-1.05742669,  1.27321553, -1.16060151, ...,  1.        ,
         5.        ,  6.        ],
       [-0.97111705,  0.16372922, -1.16060151, ...,  4.        ,
         1.        ,  2.        ],
       [ 0.08617604, -0.39101393, -0.63837898, ...,  4.        ,
         2.        ,  1.        ],
       ...,
       [-0.12959806, -2.05524339, -0.11615646, ...,  1.        ,
         0.        ,  3.        ],
       [ 0.34510496,  4.23184568,  1.4505111 , ...,  0.        ,
         0.        ,  1.        ],
       [-0.02171101,  0.07127203, -1.68282403, ...,  4.        ,
         1.        ,  2.        ]])

In [119]:
preprocessor.get_feature_names_out()

array(['num_pipeline__carat', 'num_pipeline__depth',
       'num_pipeline__table', 'num_pipeline__x', 'num_pipeline__y',
       'num_pipeline__z', 'cat_pipeline__cut', 'cat_pipeline__color',
       'cat_pipeline__clarity'], dtype=object)

In [120]:
X_train=pd.DataFrame(preprocessor.fit_transform(X_train),columns=preprocessor.get_feature_names_out())
X_test=pd.DataFrame(preprocessor.transform(X_test),columns=preprocessor.get_feature_names_out())

In [121]:
X_train

,num_pipeline__carat,num_pipeline__depth,num_pipeline__table,num_pipeline__x,num_pipeline__y,num_pipeline__z,cat_pipeline__cut,cat_pipeline__color,cat_pipeline__clarity
0,-0.604301,0.626015,-1.160602,-0.534269,-0.514894,-0.467873,4.0,0.0,3.0
1,0.560879,0.348644,-0.638379,0.708639,0.726907,0.748108,4.0,4.0,2.0
2,0.129331,0.718472,-0.116156,0.312349,0.282759,0.357257,4.0,0.0,1.0
3,-0.151175,-0.113642,-0.638379,0.069172,0.028960,0.038786,4.0,2.0,2.0
4,-0.820075,0.348644,-1.160602,-0.831486,-0.859335,-0.815296,4.0,2.0,6.0
...,...,...,...,...,...,...,...,...,...
135496,-1.014272,0.533558,-0.116156,-1.191749,-1.185648,-1.148243,4.0,5.0,6.0
135497,0.604034,0.071272,0.406066,0.744665,0.772228,0.762584,4.0,3.0,3.0
135498,0.733498,-1.315586,0.406066,0.933803,0.890063,0.762584,2.0,3.0,3.0
135499,-1.057427,0.441101,0.406066,-1.281815,-1.276291,-1.235099,4.0,1.0,5.0
135500,-1.186891,0.533558,0.406066,-1.615059,-1.584475,-1.539094,2.0,2.0,5.0

In [122]:
X_test

,num_pipeline__carat,num_pipeline__depth,num_pipeline__table,num_pipeline__x,num_pipeline__y,num_pipeline__z,cat_pipeline__cut,cat_pipeline__color,cat_pipeline__clarity
0,-1.057427,1.273216,-1.160602,-1.290822,-1.276291,-1.191671,1.0,5.0,6.0
1,-0.971117,0.163729,-1.160602,-1.110690,-1.158455,-1.119291,4.0,1.0,2.0
2,0.086176,-0.391014,-0.638379,0.276323,0.309952,0.270402,4.0,2.0,1.0
3,-0.496414,0.163729,-1.160602,-0.363144,-0.360802,-0.352065,4.0,3.0,3.0
4,-1.165314,0.348644,0.406066,-1.543006,-1.530089,-1.495666,2.0,2.0,5.0
...,...,...,...,...,...,...,...,...,...
58067,-1.014272,-0.760843,-0.638379,-1.137710,-1.113134,-1.177195,4.0,4.0,3.0
58068,-1.035849,1.088301,-0.116156,-1.245789,-1.285355,-1.177195,4.0,1.0,2.0
58069,-0.129598,-2.055243,-0.116156,0.123211,0.173988,-0.048070,1.0,0.0,3.0
58070,0.345105,4.231846,1.450511,0.231290,0.183052,0.762584,0.0,0.0,1.0
58071,-0.021711,0.071272,-1.682824,0.186257,0.210245,0.198022,4.0,1.0,2.0

In [123]:
"""linear regression
ridge regression
lasso regression
elastic net"""

'linear regression\nridge regression\nlasso regression\nelastic net'

In [124]:
## Model Training

from sklearn.linear_model import LinearRegression,Lasso,Ridge,ElasticNet
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error
import numpy as np
def evaluate_model(true, predicted):
    mae = mean_absolute_error(true, predicted)
    mse = mean_squared_error(true, predicted)
    rmse = np.sqrt(mean_squared_error(true, predicted))
    r2_square = r2_score(true, predicted)
    return mae, rmse, r2_square

In [125]:
## Train multiple models

models={
    'LinearRegression':LinearRegression(),
    'Lasso':Lasso(),
    'Ridge':Ridge(),
    'Elasticnet':ElasticNet()
}

In [126]:
trained_model_list=[]
model_list=[]
r2_list=[]

In [127]:
list(models)

['LinearRegression', 'Lasso', 'Ridge', 'Elasticnet']

In [128]:
for i in range(len(list(models))):
    model=list(models.values())[i]
    print(model)

LinearRegression()
Lasso()
Ridge()
ElasticNet()

In [129]:
models.keys()

dict_keys(['LinearRegression', 'Lasso', 'Ridge', 'Elasticnet'])

In [130]:
models.values()

dict_values([LinearRegression(), Lasso(), Ridge(), ElasticNet()])

In [134]:
for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(X_train,Y_train)

    #Make Predictions
    y_pred=model.predict(X_test)

    #this is a validation(test) score
    mae, rmse, r2_square=evaluate_model(Y_test,y_pred)

    print(list(models.keys())[i])
    model_list.append(list(models.keys())[i])

    print('Model Training Performance')
    print("RMSE:",rmse)
    print("MAE:",mae)
    print("R2 score",r2_square*100)

    r2_list.append(r2_square)
    
    print('='*35)
    print('\n')

LinearRegression
Model Training Performance
RMSE: 1005.6840940105421
MAE: 674.1964350383388
R2 score 93.75439741565778
===================================


Lasso
Model Training Performance
RMSE: 1006.0040019005428
MAE: 675.6015394375831
R2 score 93.7504233340532
===================================


Ridge
Model Training Performance
RMSE: 1005.6903915299217
MAE: 674.2313931364497
R2 score 93.75431919641042
===================================


Elasticnet
Model Training Performance
RMSE: 1514.4759780964464
MAE: 1054.069310058952
R2 score 85.83632471281206
===================================

In [135]:
trained_model_list

[]

In [136]:
model_list

['LinearRegression', 'Lasso', 'Ridge', 'Elasticnet']

In [137]:
r2_list

[0.9375439741565778, 0.937504233340532, 0.9375431919641042, 0.8583632471281206]